### ISSUE TITLE
Instructor Feedback - Week 5 - Hibernate one-to-many 

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [En-8/brew-book#2]
- [x] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertEquals(expectedUser., actualUser);` so that you don't have to compare each instance var/column manually.
- [x] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly.
- [x] Regarding this todo: https://github.com/En-8/brew-book/blob/749cbfac6e59560f04a502674fad50363dc388ef/src/test/java/dev/innate/persistance/BrewDaoTest.java#L41-L46. Refer to the generic dao's get by property (can do with a like or equals). 
- [x] A couple more one-to-many cases to test: If a user is deleted, what happens to their brews? If a brew is deleted, what happens to the user?  Use unit tests to ensure what should happen actually happens.

**Comment by En-8** [comment]
Thanks for the feedback! I implemented findByPropertyEquals in my generic dao and added test cases to cover the one-to-many relationship.
