### ISSUE TITLE
Yia's Feedback

### ISSUE THREAD

**Issue by yiax** [En-8/brew-book#4]
# Design/Code Review 1

### Reviewer: Yia Xiong

|Item |Considerations| Comments/Suggestions|
|---|---|---|
| | |Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|The problem statement adresses and explain the issue well. This application as a solution was written at a very high level. I would recommend expanding on how this application will resolve the issues that were address. It would also be helpful to explain how the application will work.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |Based on the wireframes, it seems you have a good vision of what your application intend to do. One thing I was unsure of is a landing page after the user login; I was unclear which wireframe is to represent this or maybe it may have been overlooked. Secondly, based on the New Brew (standard) wireframe, it looks as the elements on this page will create an instance of a Brew. However, the Brew entity doesn't seem to include all instance variables for all the elements on this page. I could be wrong since you do not have all the your entities created yet.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The wireframe pages indicates a plan for the database design. In addition, the Brew and User entities indicate a one to many relationship which is good. The current Brew entity is holding a yeastID with a TODO not as it being a one-to-many relationship. During class, we talked a little about how a user can add multiple fermentables and how this can be design in the database. Just a thought, can a brew hold a list of fermentables; therefore a user can add as many as needed.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.| The current code for the entities and persistence classes looks good. As an initial feedback, maybe look to implement a generic dao.|

**Comment by pawaitemadisoncollege** [comment]
Are there any system.out.printlns or printstacktraces to replace with logging statements?
